#!/usr/bin/env bash
# Hugo wrapper
set -eu -o pipefail

# MacOS lover's, I did not forget you ;)
PROJECT_ROOT="$(cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
cd "$PROJECT_ROOT"

not_found=0
HUGO=$(which hugo) || not_found=$?
if [[ $not_found -ne 0 ]]; then
  if [[ ! -d .hugo ]]; then
    mkdir .hugo
    curl -L https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_linux_amd64.tar.gz | \
      (cd .hugo; tar xzf -)
  fi
  HUGO=".hugo/hugo_0.15_linux_amd64/hugo_0.15_linux_amd64"
fi

"$HUGO" "$@"
